# Generated by Django 2.2.7 on 2019-11-13 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rfid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_rfid', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'Rfid',
            },
        ),
    ]
