# Generated by Django 2.2.7 on 2019-11-13 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_alumno', models.ForeignKey(on_delete=models.SET(-1), to='Alumno.Alumno')),
            ],
            options={
                'db_table': 'Asistencia',
            },
        ),
    ]
