# Generated by Django 2.2.7 on 2019-11-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rfid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=60)),
                ('id_rfid', models.ForeignKey(on_delete=models.SET(-1), to='Rfid.Rfid')),
            ],
            options={
                'db_table': 'Alumno',
            },
        ),
    ]
